branches:
  only:
    - master

install:
  - ps: |
      Install-PackageProvider -Name NuGet -Force | Out-Null
      Install-Module PsScriptAnalyzer -Force
      Install-Module -Name Pester -Force

environment:
  ModuleName: Posh-Datadog
  NuGetApiKey:
    secure: 9g0XGamfdzplyiYGs//sZteLfHaeciZve6EAYfIOqKWfgmS++0CFW9s8q7PdD+JA

build: false

test_script:
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - ps: |
      import-module ./ -Verbose
      try{ Publish-Module -Name $env:ModuleName -NuGetApiKey $env:NuGetApiKey }
      catch{ Write-Warning "Not publishing to PowerShellGallery. $($_.Exception.Message)" }
